services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/6333"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/cache:/app/.cache
    environment:
      - QDRANT_HOST=qdrant
      #- OpenRouter__ApiKey=sk-or-v1-
      - OpenRouter__Endpoint=https://openrouter.ai/api/v1/
      - OpenRouter__Model=nvidia/llama-nemotron-embed-vl-1b-v2:free
      #- Llm__ApiKey=sk-
      - Llm__Endpoint=https://api.deepseek.com/v1/
      - Llm__ChatModelId=deepseek-v4-flash
    depends_on:
      qdrant:
        condition: service_healthy
